// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgTRUdiglxQ4vimJe6VlCMDgosXvD1uA',
    appId: '1:5875574968:web:89915a65ce9a1a1909ac4d',
    messagingSenderId: '5875574968',
    projectId: 'traveleaze-e2f45',
    authDomain: 'traveleaze-e2f45.firebaseapp.com',
    storageBucket: 'traveleaze-e2f45.firebasestorage.app',
    measurementId: 'G-YML9XQE7SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_IQvGAbbZXohXcUfcP1Y7SbRAIbRvVM',
    appId: '1:5875574968:android:1bb5c9c5081ad46809ac4d',
    messagingSenderId: '5875574968',
    projectId: 'traveleaze-e2f45',
    storageBucket: 'traveleaze-e2f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEjJfKLVYK2GO6wsdlWkPHKllATU39c7Y',
    appId: '1:5875574968:ios:99555e607fdc78aa09ac4d',
    messagingSenderId: '5875574968',
    projectId: 'traveleaze-e2f45',
    storageBucket: 'traveleaze-e2f45.firebasestorage.app',
    iosBundleId: 'com.example.traveleaze',
  );
}
